version: '3'
services:
  app:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=production
      - PORT=5000